# Generated by Django 3.0.2 on 2020-07-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_application_permission_staffhistory_studenthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='attached_file',
            field=models.FileField(default='default.jpg', upload_to='attached_files'),
        ),
    ]
