# Generated by Django 3.0.2 on 2020-07-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200724_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='attached_file',
            field=models.FileField(default='default1.txt', upload_to='attached_files'),
        ),
    ]
