# Generated by Django 3.0.2 on 2020-07-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200724_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='attached_file',
            field=models.FileField(default='defaultFile.png', upload_to='attached_files'),
        ),
    ]
