# Generated by Django 3.0.2 on 2020-07-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200725_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='status',
            field=models.TextField(default=''),
        ),
    ]
