# Generated by Django 3.0.2 on 2020-07-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_permission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='status',
            field=models.TextField(default='Active'),
        ),
    ]
